<?php
echo "<html>\n";
echo "<head>\n";
echo "<title>Circle K UCI</title>\n";
echo "<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"images/favicon.ico\"/>\n";
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\n";
echo "<style type=\"text/css\">\n";
echo "body {\n";
echo "	background-color: #000;\n";
echo "}\n";
echo "</style>\n";
echo "<style type=\"text/css\">\n";
echo "a:link {\n";
echo "COLOR: #FFF;\n";
echo "}\n";
echo "a:visited {\n";
echo "color: #FFF;\n";
echo "}\n";
echo "a:hover {\n";
echo "COLOR: #666;\n";
echo "}\n";
echo "a:active {\n";
echo "COLOR: #666;\n";
echo "}\n";
echo "</style> \n";
echo "<style>\n";
echo "table > thead {\n";
echo "	background-color:#300;\n";
echo "	color:#FFF;\n";
echo "	font-size:30px;\n";
echo "}\n";
echo "	\n";
echo "table > tbody {\n";
echo "	color:#FFF;\n";
echo "	font-family: \"Monotype Corsiva\";\n";
echo "	text-align: left;\n";
echo "	margin-left:2px;\n";
echo "	font-size:16px;\n";
echo "}\n";
echo "table > tr > th {\n";
echo "	font-family: \"Monotype Corsiva\";\n";
echo "}\n";
echo "</style>\n";
echo "<link href=\"splashevent.css\" rel=\"stylesheet\" type=\"text/css\">\n";
echo "</head>\n";
echo "<body bgcolor=\"#FFFFFF\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\n";
echo "<!-- Save for Web Slices (splashscreennew.psd) -->\n";
echo "<table width=\"1201\" height=\"1051\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" id=\"Table_01\">\n";
echo "	<tr>\n";
echo "		<td colspan=\"7\">\n";
echo "			<img src=\"images/Peteysplash_01.jpg\" width=\"295\" height=\"48\" alt=\"\"></td>\n";
echo "		<td colspan=\"6\" rowspan=\"2\">\n";
echo "			<img src=\"images/Peteysplash_02.png\" width=\"905\" height=\"184\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"48\" alt=\"\"></td>\n";
echo "	</tr>\n";
echo "	<tr>\n";
echo "		<td rowspan=\"9\">\n";
echo "			<img src=\"images/Peteysplash_03.jpg\" width=\"37\" height=\"934\" alt=\"\"></td>\n";
echo "		<td colspan=\"6\" rowspan=\"2\"><a href=\"PeteyIndex.html\"><img src=\"images/Peteysplash_04.jpg\" width=\"258\" height=\"165\" alt=\"\"></a></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"136\" alt=\"\"></td>\n";
echo "	</tr>\n";
echo "	<tr>\n";
echo "		<td colspan=\"6\" rowspan=\"2\">\n";
echo "			<img src=\"images/Peteysplash_05.jpg\" width=\"905\" height=\"66\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"29\" alt=\"\"></td>\n";
echo "	</tr>\n";
echo "	<tr>\n";
echo "		<td colspan=\"6\">\n";
echo "			<img src=\"images/Peteysplash_06.jpg\" width=\"258\" height=\"37\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"37\" alt=\"\"></td>\n";
echo "	</tr>\n";
echo "	<tr>\n";
echo "		<td colspan=\"8\" rowspan=\"2\">\n";
echo "			<img src=\"images/Peteysplash_07.jpg\" width=\"455\" height=\"133\" alt=\"\"></td>\n";
echo "		<td><a href=\"PeteyIndex.html\"><img src=\"images/Peteysplash_08.jpg\" width=\"208\" height=\"123\" alt=\"\"></a></td>\n";
echo "		<td rowspan=\"2\">\n";
echo "			<img src=\"images/Peteysplash_09.jpg\" width=\"357\" height=\"133\" alt=\"\"></td>\n";
echo "		<td colspan=\"2\" rowspan=\"5\">\n";
echo "			<img src=\"images/Peteysplash_10.jpg\" width=\"143\" height=\"655\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"123\" alt=\"\"></td>\n";
echo "	</tr>\n";
echo "	<tr>\n";
echo "		<td>\n";
echo "			<img src=\"images/Peteysplash_11.jpg\" width=\"208\" height=\"10\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"></td>\n";
echo "	</tr>\n";
echo "	<tr>\n";
echo "		<td colspan=\"2\" rowspan=\"2\">\n";
echo "			<img src=\"images/Peteysplash_12.jpg\" width=\"118\" height=\"493\" alt=\"\"></td>\n";
echo "		<td colspan=\"7\">\n";
echo "			<img src=\"images/Peteysplash_13.jpg\" width=\"545\" height=\"123\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/Peteysplash_14.jpg\" width=\"357\" height=\"123\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"123\" alt=\"\"></td>\n";
echo "	</tr>\n";
echo "	<tr>\n";
echo "		<td>\n";
echo "			<img src=\"images/Peteysplash_15.jpg\" width=\"9\" height=\"370\" alt=\"\"></td>\n";
echo "		<td colspan=\"7\"><div id=\"splashevent\">\n";
echo "        <table width=\"882\" cellspacing=\"10\">\n";
echo "        <thead><tr>\n";
echo "        \n";
echo "	       <th width=\"231\" height=\"34\">Service</th> <th width=\"300\">Socials</th> <th width=\"303\">Others</th>\n";
echo "        </tr></thead>\n";
echo "		<tbody><tr>&nbsp\n";
echo "        	<td>[9/27] <a href=\"Peteycalendar.html\">Book Doctor</a><br>\n";
echo "            	[9/28] <a href=\"Peteycalendar.html\">Hemopet</a><br>\n";
echo "                [9/29] <a href=\"Peteycalendar.html\">OC Children\'s Book Festival</a><br>\n";
echo "                [9/30] <a href=\"Peteycalendar.html\">OC Children\'s Book Festival</a><br>\n";
echo "                &nbsp <br>\n";
echo "                &nbsp <br>\n";
echo "                &nbsp <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "			</td> \n";
echo "            <td>[9/25] <a href=\"Peteycalendar.html\">Late Night at the Arc</a><br>\n";
echo "            	[9/25] <a href=\"Peteycalendar.html\">Eat-For-Service: Cha for Tea</a><br>\n";
echo "				[9/26] <a href=\"Peteycalendar.html\">Eat-For-Service: Berkeley Dog</a><br>\n";
echo "                [9/27] <a href=\"Peteycalendar.html\">Target Late Night Social</a><br>\n";
echo "                &nbsp <br>\n";
echo "                &nbsp <br>\n";
echo "                &nbsp <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "            </td> \n";
echo "            \n";
echo "            <td>[Form] Membership Application <br>\n";
echo "				[Website] <a href=\"Super Smash Bros Site/Design/SSB_index.php\">2011-12 Super Smash Bros. Website</a><br>\n";
echo "                [Website] <a href=\"Super Smash Bros Site/Design/10_11site/index.html\">2010-11 Lion King Website</a> <br>\n";
echo "                [Follow Us] <a href=\"http://www.facebook.com/groups/242970149059638/\">Facebook</a> <br>\n";
echo "                [Follow Us] <a href=\"http://ucicki.tumblr.com/\">Tumblr</a> <br>\n";
echo "                [Follow Us] <a href=\"http://www.flickr.com/photos/ucicirclek/sets/\">Flickr</a><br>\n";
echo "                &nbsp <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "                <br>\n";
echo "            </td>\n";
echo "            \n";
echo "            \n";
echo "        </tr></tbody>\n";
echo "        </table>\n";
echo "        <img src=\"title_images/bar2.png\" width=\"893\" height=\"24\"></div></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"370\" alt=\"\"></td>\n";
echo "	</tr>\n";
echo "	<tr>\n";
echo "		<td rowspan=\"2\">\n";
echo "			<img src=\"images/Peteysplash_17.jpg\" width=\"28\" height=\"106\" alt=\"\"></td>\n";
echo "		<td colspan=\"2\" rowspan=\"2\"><a href=\"http://www.facebook.com/group.php?gid=2205624639\"><img src=\"images/Peteysplash_18.jpg\" width=\"99\" height=\"106\" alt=\"\"></a></td>\n";
echo "		<td rowspan=\"2\"><a href=\"http://www.cnhcirclek.org/\"><img src=\"images/Peteysplash_19.jpg\" width=\"120\" height=\"106\" alt=\"\"></a></td>\n";
echo "		<td rowspan=\"2\">\n";
echo "			<img src=\"images/Peteysplash_20.jpg\" width=\"1\" height=\"106\" alt=\"\"></td>\n";
echo "		<td colspan=\"2\" rowspan=\"2\"><a href=\"http://www.circlek.org/home.aspx\"><img src=\"images/Peteysplash_21.jpg\" width=\"114\" height=\"106\" alt=\"\"></a></td>\n";
echo "		<td colspan=\"3\">\n";
echo "			<img src=\"images/Peteysplash_22.jpg\" width=\"658\" height=\"29\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"29\" alt=\"\"></td>\n";
echo "	</tr>\n";
echo "	<tr>\n";
echo "		<td colspan=\"4\">\n";
echo "			<img src=\"images/Peteysplash_23.jpg\" width=\"800\" height=\"77\" alt=\"\"></td>\n";
echo "		<td rowspan=\"2\">\n";
echo "			<img src=\"images/Peteysplash_24.jpg\" width=\"1\" height=\"145\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"77\" alt=\"\"></td>\n";
echo "	</tr>\n";
echo "	<tr>\n";
echo "		<td colspan=\"12\">\n";
echo "			<img src=\"images/Peteysplash_25.jpg\" width=\"1199\" height=\"68\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"68\" alt=\"\"></td>\n";
echo "	</tr>\n";
echo "	<tr>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"37\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"28\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"90\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"9\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"120\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"10\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"104\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"93\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"208\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"357\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"142\" height=\"1\" alt=\"\"></td>\n";
echo "		<td>\n";
echo "			<img src=\"images/spacer.gif\" width=\"1\" height=\"1\" alt=\"\"></td>\n";
echo "		<td></td>\n";
echo "	</tr>\n";
echo "</table>\n";
echo "<!-- End Save for Web Slices -->\n";
echo "</body>\n";
echo "</html>\n";
?>